version: '3.3'

services:

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
#     volumes:
#       - ./dreamlab-test/wp:/var/www/html/
     networks:
          - wp
     ports:
       - "8080:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress

   db:
     image: mysql:8.0
     networks:
          - wp
#     volumes:
#       -  ./dreamlab-test/db:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
networks:
    wp:
